stylesheets:
  common:
    - public/stylesheets/reset.css
    - public/stylesheets/960.css
    - public/stylesheets/application.css
    - public/stylesheets/bills.css
    - public/stylesheets/breadcrumb.css
    - public/stylesheets/classes.css
    - public/stylesheets/forms.css
    - public/stylesheets/formtastic.css
    - public/stylesheets/formtastic_changes.css
    - public/stylesheets/colorbox.css
    - public/stylesheets/html5.css
    - public/stylesheets/jquery-ui-1.8.4.css
    - public/stylesheets/layout.css
    - public/stylesheets/people.css
    - public/stylesheets/sharing.css
    - public/stylesheets/tipsy.css

    - public/stylesheets/type.css
    - public/stylesheets/vote.css

  other:
    - public/stylesheets/vote.css
    - public/stylesheets/twitter.css
    - public/stylesheets/find_box.css
  
javascripts:
  common:
    - public/javascripts/jquery.rails.js
    - public/javascripts/jquery.timeago.js
    - public/javascripts/jquery.tipsy.js
    - public/javascripts/jquery.colorbox.js
    - public/javascripts/tracker.js
    - public/javascripts/application.js
    - public/javascripts/twitter.js
    - public/javascripts/bitly.js
    