template_function: _.template

stylesheets:
  common:
    - public/stylesheets/normalize.css
    - public/stylesheets/960.css
    - public/stylesheets/layout.css
    - public/stylesheets/type.css
    - public/stylesheets/application.css
    - public/stylesheets/breadcrumb.css
    - public/stylesheets/forms.css
    - public/stylesheets/formtastic.css
    - public/stylesheets/formtastic_changes.css
    - public/stylesheets/colorbox.css
    - public/stylesheets/tipsy.css
    - public/stylesheets/jquery-ui-1.8.4.css
    - public/stylesheets/jquery-ui-tabs.css
    - public/stylesheets/print.css
    - public/stylesheets/bills.css
    - public/stylesheets/classes.css
    - public/stylesheets/people.css
    - public/stylesheets/sharing.css
    - public/stylesheets/vote.css

  ie8:
    - public/stylesheets/ie8.css

  other:
    - public/stylesheets/vote.css
    - public/stylesheets/twitter.css
    - public/stylesheets/find_box.css

  viewer:
    - public/stylesheets/DV/components/reset.css
    - public/stylesheets/DV/components/structure.css
    - public/stylesheets/DV/components/ui.css
    - public/stylesheets/DV/components/*.css
    - public/stylesheets/DV/themes/plain.css

  viewer_print:
    - public/stylesheets/DV/print.css

  widget:
    - public/stylesheets/widget.css

javascripts:
  common:
    - public/javascripts/rails.js
    - public/javascripts/jquery/jquery.timeago.js
    - public/javascripts/jquery/jquery.tipsy.js
    - public/javascripts/jquery/jquery.colorbox.js
    - public/javascripts/jquery/jquery.placeholder.js
    - public/javascripts/tracker.js
    - public/javascripts/dropdown.js
    - public/javascripts/twitter.js
    - public/javascripts/application.js

  viewer:
    - public/javascripts/DV/vendor/jquery-1.5.1.js
    - public/javascripts/DV/vendor/jquery-ui-1.8.1.custom.min.js
    - public/javascripts/DV/vendor/underscore.js
    - public/javascripts/DV/vendor/jquery.acceptInput.js
    - public/javascripts/DV/vendor/jquery.placeholder.js
    - public/javascripts/DV/lib/initializer.js
    - public/javascripts/DV/lib/*.js
    - public/javascripts/DV/schema/*.js
    - public/javascripts/DV/elements/*.js
    - public/javascripts/DV/models/*.js
    - public/javascripts/DV/events/events.js
    - public/javascripts/DV/events/View*.js
    - public/javascripts/DV/events/*.js
    - public/javascripts/DV/helpers/helpers.js
    - public/javascripts/DV/helpers/*.js
    - public/javascripts/DV/states/*.js
    - public/javascripts/DV/controllers/*.js

  zeroclipboard:
    - public/javascripts/ZeroClipboard.js

  widget:
    - public/javascripts/underscore-1.1.6.js
    - app/views/widgets/*.jst
    - public/javascripts/widget.js

  templates:
    - public/javascripts/DV/views/*.jst

  # Widget configuration tools
  widget_config:
    - public/javascripts/underscore-1.1.6.js
    - app/views/widgets/*.jst
    - public/javascripts/widget.js
    - public/javascripts/jscolor.js
    - public/javascripts/json2.js
    - public/javascripts/widget.config.js
