stylesheets:
  blueprint:
    - public/stylesheets/blueprint.css
  basic:
    - public/stylesheets/html5.css
    - public/stylesheets/formtastic.css
    - public/stylesheets/formtastic_changes.css
    - public/stylesheets/blueprint.css
    - public/stylesheets/forms.css
    - public/stylesheets/sharing.css
